name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: grid test
      id: grid-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: grid test
        setup-command: cd battleship
        command: gradle runGridTest
        timeout: 10
        max-score: 10
    - name: freebie
      id: freebie
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: freebie
        setup-command: cd battleship
        command: " gradle -p ./battleship runFreebieTest"
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GRID-TEST_RESULTS: "${{steps.grid-test.outputs.result}}"
        FREEBIE_RESULTS: "${{steps.freebie.outputs.result}}"
      with:
        runners: grid-test,freebie
